# Generated by Django 5.2.17 on 2026-08-24 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def prepare_non_first_wave(apps, schema_editor):
    federative_unit = apps.get_model("territories", "FederativeUnit")
    federative_unit.objects.filter(commercial_status="NATIONAL_READY").update(
        commercial_status="PREPARATION"
    )


def restore_legacy_status(apps, schema_editor):
    federative_unit = apps.get_model("territories", "FederativeUnit")
    federative_unit.objects.filter(commercial_status="PREPARATION").update(
        commercial_status="NATIONAL_READY"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='federativeunit',
            old_name='operational_status',
            new_name='commercial_status',
        ),
        migrations.AlterField(
            model_name='federativeunit',
            name='commercial_status',
            field=models.CharField(choices=[('PREPARATION', 'Preparação'), ('FIRST_WAVE', 'Primeira onda'), ('ACTIVE', 'Ativa'), ('PAUSED', 'Pausada')], default='PREPARATION', max_length=20),
        ),
        migrations.RunPython(prepare_non_first_wave, restore_legacy_status),
        migrations.RemoveField(
            model_name='federativeunit',
            name='commercially_active',
        ),
        migrations.CreateModel(
            name='RegulatoryReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(max_length=50)),
                ('capability', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NOT_REVIEWED', 'Não revisada'), ('RESEARCHING', 'Em pesquisa'), ('REVIEW_REQUIRED', 'Revisão necessária'), ('APPROVED', 'Aprovada'), ('SUSPENDED', 'Suspensa')], default='NOT_REVIEWED', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('federative_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_readiness', to='territories.federativeunit')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('federative_unit', 'provider_type', 'capability'), name='uq_regulatory_readiness_scope')],
            },
        ),
    ]
