# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("territories", "0002_remove_federativeunit_commercially_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "país", "verbose_name_plural": "países"},
        ),
        migrations.AlterModelOptions(
            name="federativeunit",
            options={
                "ordering": ["code"],
                "verbose_name": "unidade federativa",
                "verbose_name_plural": "unidades federativas",
            },
        ),
        migrations.AlterModelOptions(
            name="regulatoryreadiness",
            options={
                "verbose_name": "prontidão regulatória",
                "verbose_name_plural": "registros de prontidão regulatória",
            },
        ),
    ]
