FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.28-alpine
COPY nginx.demo.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/instrutorpro/browser /usr/share/nginx/html
EXPOSE 8080
