# Generated by Django 5.2.17 on 2026-08-30 09:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0004_codex_02e_workflow'),
        ('people', '0002_role_assignment_history_and_authorization'),
        ('territories', '0002_remove_federativeunit_commercially_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=8)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(max_length=12)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='discovery.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('intended_category', models.CharField(default='B', max_length=8)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to='people.person')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='territories.federativeunit')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('private_centroid', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('radius_km', models.PositiveSmallIntegerField(default=10)),
                ('transmission', models.CharField(blank=True, max_length=12)),
                ('availability', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='ACTIVE', max_length=12)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='territories.federativeunit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='marketplace.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LessonRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=8)),
                ('preferred_period', models.CharField(blank=True, max_length=80)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceita'), ('REJECTED', 'Rejeitada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=12)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requests', to='discovery.instructorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_requests', to='marketplace.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorPrerequisiteAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_version', models.CharField(max_length=40)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_acceptances', to='discovery.instructorprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instructor', 'policy_version'), name='uq_instructor_prerequisite_version')],
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['uf', 'city', 'data_mode'], name='marketplace_uf_id_99485d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdemand',
            index=models.Index(fields=['status', 'data_mode', 'uf', 'city'], name='marketplace_status_06a65b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonrequest',
            index=models.Index(fields=['instructor', 'status', 'created_at'], name='marketplace_instruc_313193_idx'),
        ),
    ]
