# Generated by Django 5.2.17 on 2026-08-31 10:47

import apps.marketplace.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_codex_02e_workflow'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorvehicle',
            name='ownership_type',
            field=models.CharField(default='AVAILABLE_TO_INSTRUCTOR', max_length=24),
        ),
        migrations.AddField(
            model_name='instructorvehicle',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Vencido')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=8)),
                ('provider_type', models.CharField(default='INSTRUCTOR', max_length=24)),
                ('rule_version', models.CharField(max_length=40)),
                ('document_type', models.CharField(choices=[('INSTRUCTOR_AUTHORIZATION', 'Autorização/credencial de instrutor'), ('INSTRUCTOR_COURSE', 'Certificado de curso de instrutor'), ('VEHICLE_EVIDENCE', 'Documento/evidência do veículo'), ('OTHER', 'Outro requisito territorial')], max_length=40)),
                ('label', models.CharField(max_length=160)),
                ('required', models.BooleanField(default=True)),
                ('requires_validity', models.BooleanField(default=False)),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('uf', 'category', 'provider_type', 'rule_version', 'document_type'), name='uq_document_requirement_rule'), models.CheckConstraint(condition=models.Q(('active_until__isnull', True), ('active_until__gte', models.F('active_from')), _connector='OR'), name='ck_document_requirement_dates')],
            },
        ),
        migrations.CreateModel(
            name='InstructorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issuer', models.CharField(blank=True, max_length=160)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('file', models.FileField(max_length=300, upload_to=apps.marketplace.models.private_document_path)),
                ('original_name', models.CharField(max_length=180)),
                ('mime_type', models.CharField(max_length=80)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Vencido')], default='PENDING', max_length=20)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Aguardando análise'), ('CLEAN', 'Fixture segura'), ('BLOCKED', 'Bloqueado')], default='PENDING', max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=240)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='discovery.instructorprofile')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='marketplace.documentrequirement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_instructor_documents', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='marketplace.instructordocument')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='marketplace.instructorvehicle')),
            ],
            options={
                'permissions': [('review_instructor_document', 'Can review instructor documents')],
                'indexes': [models.Index(fields=['instructor', 'status', 'valid_until'], name='marketplace_instruc_b1a18d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('issued_at__isnull', True), ('valid_until__gte', models.F('issued_at')), _connector='OR'), name='ck_instructor_document_dates')],
            },
        ),
    ]
