# Generated by Django 5.2.17 on 2026-08-31 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_codex_02e_workflow'),
        ('marketplace', '0002_instructorvehicle_ownership_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTrainingRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=8)),
                ('process_type', models.CharField(max_length=40)),
                ('rule_version', models.CharField(max_length=40)),
                ('minimum_minutes', models.PositiveIntegerField()),
                ('source_reference', models.CharField(max_length=300)),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('uf', 'category', 'process_type', 'rule_version'), name='uq_practical_training_rule'), models.CheckConstraint(condition=models.Q(('minimum_minutes__gt', 0)), name='ck_training_minimum_positive'), models.CheckConstraint(condition=models.Q(('active_until__isnull', True), ('active_until__gte', models.F('active_from')), _connector='OR'), name='ck_training_requirement_dates')],
            },
        ),
        migrations.CreateModel(
            name='PlatformLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada na plataforma'), ('COMPLETED', 'Concluída na plataforma'), ('CANCELLED', 'Cancelada na plataforma')], max_length=20)),
                ('official_record_status', models.CharField(choices=[('NOT_INTEGRATED', 'Sem integração oficial'), ('EXTERNALLY_DECLARED', 'Registro externo apenas declarado')], default='NOT_INTEGRATED', max_length=24)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_lessons', to='discovery.instructorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_lessons', to='marketplace.studentprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_lessons', to='marketplace.instructorvehicle')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_lessons', to='marketplace.practicaltrainingrequirement')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='ck_platform_lesson_duration_positive')],
            },
        ),
    ]
