# Generated by Django 5.2.17 on 2026-08-31 11:16

import apps.marketplace.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_codex_02e_workflow'),
        ('marketplace', '0003_practicaltrainingrequirement_platformlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructordocument',
            name='credential_uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='private_identifier',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='review_source',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=300, upload_to=apps.marketplace.models.private_profile_photo_path)),
                ('original_name', models.CharField(max_length=180)),
                ('mime_type', models.CharField(max_length=80)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada'), ('REPLACEMENT_REQUESTED', 'Substituição solicitada')], default='PENDING', max_length=24)),
                ('publication_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('publication_notice_version', models.CharField(blank=True, max_length=80)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=240)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_photos', to='discovery.instructorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_profile_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('review_profile_photo', 'Can review instructor profile photos')],
                'indexes': [models.Index(fields=['instructor', 'status', 'uploaded_at'], name='marketplace_instruc_b35d3f_idx')],
            },
        ),
    ]
