# Generated by Django 5.2.17 on 2026-09-11 12:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_codex_02e_workflow'),
        ('marketplace', '0005_studentprofile_preferred_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorContactChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_e164', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\+55[1-9][0-9]{9,10}$', 'Informe um WhatsApp brasileiro válido.')])),
                ('is_active', models.BooleanField(default=True)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contact_channel', to='discovery.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=8)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('price_type', models.CharField(choices=[('LESSON', 'Aula')], default='LESSON', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='discovery.instructorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['instructor', 'is_active', 'category'], name='marketplace_instruc_2b200d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_amount__gt', 0)), name='ck_offer_price_positive'), models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='ck_offer_duration_positive'), models.CheckConstraint(condition=models.Q(('currency', 'BRL')), name='ck_offer_currency_brl')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SEARCH_PERFORMED', 'Busca realizada'), ('SEARCH_RESULT_IMPRESSION', 'Impressão na busca'), ('INSTRUCTOR_PROFILE_VIEWED', 'Perfil visualizado'), ('WHATSAPP_CONTACT_CLICKED', 'Clique no WhatsApp')], max_length=40)),
                ('session_hash', models.CharField(max_length=64)),
                ('dedupe_bucket', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(blank=True, max_length=8)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('data_mode', models.CharField(choices=[('SYNTHETIC', 'Sintético'), ('REAL', 'Real')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_events', to='discovery.instructorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['instructor', 'event_type', 'created_at'], name='marketplace_instruc_319b69_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'instructor', 'session_hash', 'dedupe_bucket'), name='uq_marketplace_event_session_bucket', nulls_distinct=False)],
            },
        ),
    ]
