# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0008_seed_saas_catalog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentrequirement",
            options={
                "verbose_name": "requisito documental",
                "verbose_name_plural": "requisitos documentais",
            },
        ),
        migrations.AlterModelOptions(
            name="entitlement",
            options={"verbose_name": "benefício", "verbose_name_plural": "benefícios"},
        ),
        migrations.AlterModelOptions(
            name="instructorcontactchannel",
            options={
                "verbose_name": "canal de contato do instrutor",
                "verbose_name_plural": "canais de contato dos instrutores",
            },
        ),
        migrations.AlterModelOptions(
            name="instructordocument",
            options={
                "permissions": [
                    ("review_instructor_document", "Pode revisar documentos de instrutores")
                ],
                "verbose_name": "documento do instrutor",
                "verbose_name_plural": "documentos dos instrutores",
            },
        ),
        migrations.AlterModelOptions(
            name="instructoroffer",
            options={
                "verbose_name": "oferta de instrutor",
                "verbose_name_plural": "ofertas de instrutores",
            },
        ),
        migrations.AlterModelOptions(
            name="instructoronboardingdraft",
            options={
                "verbose_name": "rascunho de cadastro de instrutor",
                "verbose_name_plural": "rascunhos de cadastro de instrutor",
            },
        ),
        migrations.AlterModelOptions(
            name="instructorprerequisiteacceptance",
            options={
                "verbose_name": "aceite de pré-requisito do instrutor",
                "verbose_name_plural": "aceites de pré-requisitos dos instrutores",
            },
        ),
        migrations.AlterModelOptions(
            name="instructorvehicle",
            options={
                "verbose_name": "veículo de instrutor",
                "verbose_name_plural": "veículos de instrutores",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonrequest",
            options={
                "verbose_name": "solicitação de aula",
                "verbose_name_plural": "solicitações de aulas",
            },
        ),
        migrations.AlterModelOptions(
            name="marketplaceevent",
            options={
                "verbose_name": "evento do marketplace",
                "verbose_name_plural": "eventos do marketplace",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["display_order", "code"],
                "permissions": [("manage_saas", "Pode gerenciar planos e assinaturas")],
                "verbose_name": "plano",
                "verbose_name_plural": "planos",
            },
        ),
        migrations.AlterModelOptions(
            name="planentitlement",
            options={
                "verbose_name": "benefício do plano",
                "verbose_name_plural": "benefícios dos planos",
            },
        ),
        migrations.AlterModelOptions(
            name="platformlesson",
            options={
                "verbose_name": "aula da plataforma",
                "verbose_name_plural": "aulas da plataforma",
            },
        ),
        migrations.AlterModelOptions(
            name="practicaltrainingrequirement",
            options={
                "verbose_name": "requisito de formação prática",
                "verbose_name_plural": "requisitos de formação prática",
            },
        ),
        migrations.AlterModelOptions(
            name="profilephoto",
            options={
                "permissions": [
                    ("review_profile_photo", "Pode revisar fotos de perfis de instrutores")
                ],
                "verbose_name": "foto do perfil",
                "verbose_name_plural": "fotos dos perfis",
            },
        ),
        migrations.AlterModelOptions(
            name="studentdemand",
            options={
                "verbose_name": "demanda de aluno",
                "verbose_name_plural": "demandas de alunos",
            },
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={"verbose_name": "perfil de aluno", "verbose_name_plural": "perfis de alunos"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "assinatura", "verbose_name_plural": "assinaturas"},
        ),
    ]
