# Generated by Django 5.2.17 on 2026-09-23 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_professional_document_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructordocument',
            name='retention_status',
            field=models.CharField(choices=[('POLICY_PENDING', 'Política pendente'), ('SCHEDULED', 'Descarte agendado')], default='POLICY_PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('TEST', 'Teste técnico'), ('PRODUCTION', 'Produção')], max_length=16)),
                ('rule_version', models.CharField(max_length=40)),
                ('retention_days', models.PositiveIntegerField()),
                ('source_reference', models.CharField(max_length=240)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'política de retenção documental',
                'verbose_name_plural': 'políticas de retenção documental',
            },
        ),
        migrations.AddField(
            model_name='instructordocument',
            name='retention_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.documentretentionpolicy'),
        ),
        migrations.AddConstraint(
            model_name='documentretentionpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('scope',), name='uq_active_document_retention_policy_scope'),
        ),
        migrations.AddConstraint(
            model_name='documentretentionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('retention_days__gte', 1)), name='ck_document_retention_days_positive'),
        ),
    ]
