# Generated by Django 5.2.17 on 2026-09-27 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0009_verification_requirements_snapshot"),
        ("marketplace", "0011_document_retention_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instructordocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROFESSIONAL_CREDENTIAL", "Credencial profissional"),
                    ("PROFESSIONAL_CERTIFICATE", "Certificado/credenciamento"),
                    ("OTHER_PROFESSIONAL", "Outro documento profissional"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="instructordocument",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="marketplace.documentrequirement",
            ),
        ),
        migrations.AddConstraint(
            model_name="instructordocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requirement__isnull", False),
                    models.Q(
                        (
                            "document_type__in",
                            [
                                "PROFESSIONAL_CREDENTIAL",
                                "PROFESSIONAL_CERTIFICATE",
                                "OTHER_PROFESSIONAL",
                            ],
                        ),
                        ("verification_request__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_document_requirement_or_generic",
            ),
        ),
    ]
