import { AfterViewInit,ChangeDetectorRef,Component,ElementRef,EventEmitter,Input,OnChanges,OnDestroy,Output,SimpleChanges,ViewChild,ViewEncapsulation,inject } from '@angular/core';
import * as L from 'leaflet';
import type { Feature,FeatureCollection,Geometry } from 'geojson';
import type { DemoDemandState } from '../../demo/demo-data.providers';

interface UfProperties{codarea:string}
const UF_BY_IBGE_CODE:Readonly<Record<string,string>>={'11':'RO','12':'AC','13':'AM','14':'RR','15':'PA','16':'AP','17':'TO','21':'MA','22':'PI','23':'CE','24':'RN','25':'PB','26':'PE','27':'AL','28':'SE','29':'BA','31':'MG','32':'ES','33':'RJ','35':'SP','41':'PR','42':'SC','43':'RS','50':'MS','51':'MT','52':'GO','53':'DF'};
const ACTIVE_LABEL_POSITIONS:Readonly<Record<string,L.LatLngExpression>>={RS:[-30.15,-53.8],SC:[-27.25,-50.1],SP:[-22.35,-49.5],RJ:[-22.45,-42.75],ES:[-19.5,-40.25]};

@Component({
  selector:'app-brazil-demand-map',standalone:true,encapsulation:ViewEncapsulation.None,
  template:`<div class="brazil-map-shell"><div #mapHost class="brazil-map" aria-label="Mapa do Brasil com as 27 unidades federativas"></div><div class="brazil-map-legend"><span><i class="active"></i> Estado ativo na demo</span><span><i></i> Estado em preparação</span></div><p class="brazil-map-source">Malha territorial: IBGE · contagens sintéticas</p>@if(loadError){<p class="brazil-map-error"><i class="pi pi-exclamation-triangle"></i> Não foi possível carregar a malha do Brasil.</p>}</div>`,
  styles:[`.brazil-map-shell{position:relative;min-height:35rem;overflow:hidden;background:linear-gradient(145deg,#edf7f4,#dcece8)}.brazil-map{height:35rem;background:transparent}.brazil-map .leaflet-control-attribution{display:none}.brazil-map .leaflet-interactive:focus{outline:3px solid #ff8a42;outline-offset:1px}.brazil-map-count{display:grid!important;place-items:center;width:3.35rem!important;height:3.35rem!important;margin:-1.675rem 0 0 -1.675rem!important;border:3px solid #fff;border-radius:50%;color:#fff;background:#177e87;box-shadow:0 5px 14px #123e5840;font-size:.72rem;font-weight:850;line-height:1.05;text-align:center;cursor:pointer}.brazil-map-count strong,.brazil-map-count small{display:block}.brazil-map-count small{margin-top:.12rem;font-size:.68rem}.brazil-map-count.selected{background:#ef702b;transform:scale(1.08)}.brazil-map-legend{position:absolute;z-index:500;top:1rem;left:1rem;display:flex;gap:.85rem;flex-wrap:wrap;padding:.65rem .8rem;border-radius:.7rem;background:#fffffff0;box-shadow:0 4px 16px #173e5314;font-size:.7rem;font-weight:750}.brazil-map-legend span{display:flex;align-items:center;gap:.35rem}.brazil-map-legend i{width:.8rem;height:.8rem;border:1px solid #9ab9b3;border-radius:.2rem;background:#d8e8e4}.brazil-map-legend i.active{border-color:#177e87;background:#41a499}.brazil-map-source{position:absolute;z-index:500;bottom:.7rem;left:.8rem;margin:0;padding:.45rem .6rem;border-radius:.45rem;background:#ffffffe8;font-size:.65rem}.brazil-map-error{position:absolute;z-index:600;inset:50% auto auto 50%;margin:0;padding:1rem;border-radius:.8rem;background:#fff0ed;transform:translate(-50%,-50%)}@media(max-width:900px){.brazil-map-shell,.brazil-map{min-height:30rem;height:30rem}}@media(max-width:560px){.brazil-map-shell,.brazil-map{min-height:26rem;height:26rem}.brazil-map-legend{right:.7rem;left:.7rem}.brazil-map-count{width:2.75rem!important;height:2.75rem!important;margin:-1.375rem 0 0 -1.375rem!important;font-size:.62rem}}`]
})
export class BrazilDemandMapComponent implements AfterViewInit,OnChanges,OnDestroy{
  @Input({required:true}) states:DemoDemandState[]=[];@Input({required:true}) selectedUf='';@Output() readonly stateSelected=new EventEmitter<string>();
  @ViewChild('mapHost',{static:true}) private mapHost!:ElementRef<HTMLElement>;
  loadError=false;private readonly changeDetector=inject(ChangeDetectorRef);private map?:L.Map;private stateLayer?:L.GeoJSON;private labels=new Map<string,L.Marker>();
  async ngAfterViewInit():Promise<void>{this.map=L.map(this.mapHost.nativeElement,{attributionControl:false,zoomControl:true,scrollWheelZoom:false,doubleClickZoom:false,minZoom:3,maxZoom:6});try{const response=await fetch('/assets/maps/br-ufs.geojson');if(!response.ok)throw new Error(`HTTP ${response.status}`);const collection=await response.json() as FeatureCollection<Geometry,UfProperties>;this.renderStates(collection)}catch{this.loadError=true;this.changeDetector.detectChanges()}}
  ngOnChanges(changes:SimpleChanges):void{if(changes['selectedUf']&&this.map)this.refreshStyles()}
  ngOnDestroy():void{this.map?.remove();this.labels.clear()}
  private renderStates(collection:FeatureCollection<Geometry,UfProperties>):void{if(!this.map)return;this.stateLayer=L.geoJSON(collection,{style:feature=>this.styleFor(feature),onEachFeature:(feature,layer)=>this.bindState(feature,layer)}).addTo(this.map);this.map.fitBounds(this.stateLayer.getBounds(),{padding:[20,20]});this.renderLabels()}
  private bindState(feature:Feature<Geometry,UfProperties>,layer:L.Layer):void{const uf=UF_BY_IBGE_CODE[feature.properties.codarea];const active=this.states.find(state=>state.uf===uf);if('bindTooltip' in layer)layer.bindTooltip(active?`${uf}: ${active.total} oportunidades demo`:`${uf}: em preparação`);if(active)layer.on('click',()=>this.select(uf))}
  private renderLabels():void{if(!this.map)return;for(const state of this.states){const position=ACTIVE_LABEL_POSITIONS[state.uf];if(!position)continue;const marker=L.marker(position,{keyboard:true,title:`${state.uf}: ${state.total} oportunidades demo`,icon:this.labelIcon(state)}).on('click',()=>this.select(state.uf)).addTo(this.map);this.labels.set(state.uf,marker)}}
  private select(uf:string):void{this.selectedUf=uf;this.refreshStyles();this.stateSelected.emit(uf)}
  private refreshStyles():void{this.stateLayer?.setStyle(feature=>this.styleFor(feature));for(const state of this.states)this.labels.get(state.uf)?.setIcon(this.labelIcon(state))}
  private styleFor(feature?:Feature<Geometry,UfProperties>):L.PathOptions{const uf=feature?UF_BY_IBGE_CODE[feature.properties.codarea]:'';const active=this.states.some(state=>state.uf===uf);const selected=uf===this.selectedUf;return{color:'#fff',weight:selected?2.5:1.25,fillColor:selected?'#ef702b':active?'#41a499':'#c8ddd8',fillOpacity:selected?.95:active?.85:.72}}
  private labelIcon(state:DemoDemandState):L.DivIcon{const selectedClass=state.uf===this.selectedUf?' selected':'';return L.divIcon({className:`brazil-map-count${selectedClass}`,html:`<span><strong>${state.uf}</strong><small>${state.total}</small></span>`,iconSize:[54,54],iconAnchor:[27,27]})}
}
