import { HttpClient } from '@angular/common/http';
import { ChangeDetectorRef, Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

type Draft={current_step:number;display_name:string;email:string;transmissions:string[];vehicle_available:boolean;vehicle?:{make:string;model:string;year:number;transmission:string};service_area?:{city:string;uf:string;region:string;radius_km:number};location_authorized:boolean;photo_present:boolean;document_types:string[];profile_status:string};

@Component({selector:'app-instructor-onboarding',imports:[FormsModule,RouterLink],template:`<section class="page narrow"><div class="demo-flag">DEV/TEST · dados sintéticos persistentes</div><header class="page-head"><div><p class="eyebrow">Quero atuar como instrutor</p><h1>Cadastro profissional</h1><p>Cada etapa é salva no backend. Cadastro não significa publicação.</p></div></header><ol class="steps">@for(label of labels;track label;let i=$index){<li [class.active]="step===i+1" [class.done]="step>i+1"><b>{{i+1}}</b><span>{{label}}</span></li>}</ol>
@if(!submitted){<form class="card" (ngSubmit)="send()">
@if(step===1){<h2>1. Dados</h2><label>Nome demonstrativo<input name="name" [(ngModel)]="form.display_name" required></label><label>E-mail sintético<input name="email" type="email" [(ngModel)]="form.email" required></label><label>Senha DEV/TEST<input name="password" type="password" minlength="10" [(ngModel)]="form.password" required></label><label class="check"><input type="checkbox" name="prerequisite" [(ngModel)]="form.prerequisite_accepted"> Declaro que as informações são verdadeiras e que o cadastro será analisado antes da publicação.</label>}
@if(step===2){<h2>2. Foto do perfil</h2><p>Use uma foto atual, nítida e de frente. A foto é separada dos documentos e só poderá ser pública depois de aprovada.</p><label>Tirar foto ou enviar foto<input type="file" accept="image/png,image/jpeg" capture="user" (change)="file('profile_photo',$event)"></label><label class="check"><input type="checkbox" name="photoAuth" [(ngModel)]="form.photo_publication_authorized"> Autorizo o uso da foto sintética depois da aprovação.</label><p>Status inicial: <b>PENDENTE</b>.</p>}
@if(step===3){<h2>3. Atendimento</h2><label>Categoria<select name="category" [(ngModel)]="form.category"><option value="B">B</option></select></label><fieldset><legend>Transmissão</legend><label class="check"><input type="checkbox" name="manual" [(ngModel)]="form.manual"> Manual</label><label class="check"><input type="checkbox" name="automatic" [(ngModel)]="form.automatic"> Automática</label></fieldset><label class="check"><input type="checkbox" name="hasVehicle" [(ngModel)]="form.vehicle_available"> Possui veículo para atendimento</label>}
@if(step===4){<h2>4. Veículo</h2>@if(form.vehicle_available){<div class="two"><label>Marca<input name="make" [(ngModel)]="form.vehicle_make"></label><label>Modelo<input name="model" [(ngModel)]="form.vehicle_model"></label><label>Ano<input name="year" type="number" [(ngModel)]="form.vehicle_year"></label><label>Categoria<select name="vehicleCategory" [(ngModel)]="form.category"><option value="B">B</option></select></label><label>Transmissão<select name="vehicleTransmission" [(ngModel)]="form.vehicle_transmission"><option value="MANUAL">Manual</option><option value="AUTOMATIC">Automática</option></select></label></div><p>Nenhuma placa é solicitada ou publicada.</p>}@else{<p>Nenhum veículo informado.</p>}}
@if(step===5){<h2>5. Localização e atendimento</h2><div class="two"><label>Cidade<input name="city" [(ngModel)]="form.city"></label><label>UF<select name="uf" [(ngModel)]="form.uf"><option>RS</option><option>SC</option><option>SP</option><option>RJ</option><option>ES</option></select></label></div><label>Região/bairro<input name="region" [(ngModel)]="form.region"></label><label>Raio<select name="radius" [(ngModel)]="form.radius_km"><option [ngValue]="5">5 km</option><option [ngValue]="10">10 km</option><option [ngValue]="20">20 km</option><option [ngValue]="50">50 km</option></select></label><p>Informe somente a área pública de atendimento, nunca a residência.</p><label class="check"><input type="checkbox" name="locationAuth" [(ngModel)]="form.location_authorized"> Autorizo o uso da área de atendimento na descoberta.</label>}
@if(step===6){<h2>6. Documentos e credenciais</h2><p>Somente fixtures PDF/PNG/JPEG de até 5 MB, com nome iniciado por <b>fixture-</b>. Arquivos permanecem privados.</p><label>Identificador sintético da autorização DETRAN<input name="credentialIdentifier" [(ngModel)]="form.credential_identifier"></label><div class="two"><label>Emissão<input type="date" name="issued" [(ngModel)]="form.credential_issued_at"></label><label>Validade<input type="date" name="valid" [(ngModel)]="form.credential_valid_until"></label></div><label>Credenciamento/autorização DETRAN<input type="file" accept=".pdf,.png,.jpg,.jpeg" (change)="file('credential_file',$event)"></label><label>Certificado do curso<input type="file" accept=".pdf,.png,.jpg,.jpeg" (change)="file('course_file',$event)"></label>@if(form.vehicle_available){<label>Documento/evidência do veículo<input type="file" accept=".pdf,.png,.jpg,.jpeg" (change)="file('vehicle_file',$event)"></label>}<p>Status inicial: <b>PENDENTE</b>.</p>}
@if(step===7){<h2>7. Revise seu cadastro</h2><dl><dt>Dados</dt><dd>{{state(form.display_name&&form.email)}}</dd><dt>Foto</dt><dd>{{state(photo)}}</dd><dt>Atendimento</dt><dd>{{state(form.manual||form.automatic)}}</dd><dt>Veículo</dt><dd>{{state(!form.vehicle_available||(form.vehicle_make&&form.vehicle_model&&form.vehicle_year))}}</dd><dt>Localização</dt><dd>{{state(form.city&&form.location_authorized)}}</dd><dt>Credenciamento DETRAN</dt><dd>{{state(docs.includes('INSTRUCTOR_AUTHORIZATION'))}}</dd><dt>Curso</dt><dd>{{state(docs.includes('INSTRUCTOR_COURSE'))}}</dd><dt>Documento veículo</dt><dd>{{state(!form.vehicle_available||docs.includes('VEHICLE_EVIDENCE'))}}</dd></dl><label class="check"><input type="checkbox" name="synthetic" [(ngModel)]="form.synthetic_data_confirmed"> Confirmo que todos os dados são sintéticos.</label>}
@if(error){<p class="error">{{error}}</p>}@if(saved){<p class="saved">Progresso salvo no backend.</p>}<footer><button type="button" class="button ghost" [disabled]="step===1||sending" (click)="step=step-1">Voltar</button>@if(step<7){<button type="button" class="button primary" [disabled]="sending" (click)="next()">{{sending?'Salvando…':'Salvar e continuar'}}</button>}@else{<button class="button primary" [disabled]="sending">{{sending?'Enviando…':'Enviar para análise'}}</button>}</footer></form>}@else{<article class="submitted"><i class="pi pi-check-circle"></i><h2>Cadastro enviado</h2><p>{{name}} está disponível para análise administrativa e não foi publicado.</p><ol><li>✓ Conta criada</li><li>✓ Perfil preenchido</li><li>✓ Enviado para análise</li><li>○ Verificação</li><li>○ Aprovação</li><li>○ Publicação</li></ol><a class="button secondary" routerLink="/profissional/instrutor/status">Acompanhar status</a></article>}</section>`,styles:[`.steps{display:grid;grid-template-columns:repeat(7,1fr);gap:.3rem;padding:0;list-style:none}.steps li{display:flex;gap:.3rem;align-items:center;color:#71858b;font-size:.68rem}.steps b{display:grid;place-items:center;width:1.8rem;aspect-ratio:1;border-radius:50%;background:#dfeae8}.steps .active b,.steps .done b{color:#fff;background:#138f8d}.card,.submitted{padding:1.5rem;border:1px solid #d6e5e3;border-radius:1.2rem;background:#fff}.card label{display:flex;flex-direction:column;gap:.4rem;margin:1rem 0;font-weight:750}.card input,.card select{min-height:3rem;padding:.7rem;border:1px solid #bfd5d2;border-radius:.7rem}.two{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.check{flex-direction:row!important;align-items:center!important}.check input{min-height:auto}.card footer{display:flex;justify-content:space-between;margin-top:1.5rem}.card dl{display:grid;grid-template-columns:12rem 1fr;gap:.6rem}.card dd{margin:0}.error{color:#9a302c}.saved{color:#087565}.submitted{text-align:center}.submitted>i{font-size:4rem;color:#159985}@media(max-width:700px){.steps span{display:none}.two{grid-template-columns:1fr}.card dl{grid-template-columns:1fr}}`]})
export class InstructorOnboardingComponent{
 private http=inject(HttpClient);private cdr=inject(ChangeDetectorRef);step=1;sending=false;submitted=false;error='';saved=false;name='';photo=false;docs:string[]=[];readonly labels=['Dados','Foto','Atendimento','Veículo','Localização','Documentos','Revisão'];
 form={email:'',password:'',prerequisite_accepted:true,display_name:'',city:'',uf:'RS',region:'',category:'B',vehicle_available:false,vehicle_make:'',vehicle_model:'',vehicle_year:2024,vehicle_transmission:'MANUAL',manual:true,automatic:false,radius_km:10,location_authorized:false,credential_identifier:'',credential_issued_at:'',credential_valid_until:'',photo_publication_authorized:false,photo_notice_version:'M1-SYNTHETIC-PHOTO-NOTICE-1',synthetic_data_confirmed:false};uploads:Record<string,File|undefined>={};
 constructor(){this.http.get<Draft>('/demo/instructor-onboarding/draft/').subscribe({next:r=>{this.resume(r);this.cdr.markForCheck()},error:()=>undefined})}
 file(k:string,e:Event){const f=(e.target as HTMLInputElement).files?.[0];this.uploads[k]=f;this.error=f&&!f.name.toLowerCase().startsWith('fixture-')?'O nome da fixture deve começar por fixture-.':''}
 state(v:unknown){return v?'COMPLETO':'PENDENTE'}
 valid(){this.error='';if(this.step===1)return !!(this.form.display_name&&this.form.email.endsWith('@example.invalid')&&this.form.password.length>=10&&this.form.prerequisite_accepted);if(this.step===2)return !this.uploads['profile_photo']||this.form.photo_publication_authorized;if(this.step===3)return this.form.manual||this.form.automatic;if(this.step===4)return !this.form.vehicle_available||!!(this.form.vehicle_make&&this.form.vehicle_model&&this.form.vehicle_year);if(this.step===5)return !!(this.form.city&&this.form.location_authorized);return true}
 next(){if(!this.valid()){this.error='Complete os campos obrigatórios desta etapa.';return}if(Object.values(this.uploads).some(f=>f&&!f.name.toLowerCase().startsWith('fixture-'))){this.error='Use somente fixtures prefixadas por fixture-.';return}this.sending=true;this.saved=false;this.http.post<Draft>('/demo/instructor-onboarding/draft/',this.body()).subscribe({next:r=>{this.sending=false;this.saved=true;this.uploads={};this.resume(r);this.cdr.markForCheck()},error:e=>{this.sending=false;this.error=e.error?.email?.[0]||e.error?.detail||'Não foi possível salvar.';this.cdr.markForCheck()}})}
 body(){const points:Record<string,[number,number]>={RS:[-30.0346,-51.2177],SC:[-27.5949,-48.5482],SP:[-23.5505,-46.6333],RJ:[-22.9068,-43.1729],ES:[-20.3155,-40.3128]};const [latitude,longitude]=points[this.form.uf],b=new FormData(),d:any={...this.form,step:this.step,transmissions:[this.form.manual?'MANUAL':null,this.form.automatic?'AUTOMATIC':null].filter(Boolean),latitude,longitude};Object.entries(d).forEach(([k,v])=>Array.isArray(v)?v.forEach(x=>b.append(k,String(x))):b.append(k,String(v)));Object.entries(this.uploads).forEach(([k,v])=>{if(v)b.append(k,v)});return b}
 resume(r:Draft){this.step=r.current_step;this.name=r.display_name;this.form.display_name=r.display_name||this.form.display_name;this.form.email=r.email||this.form.email;this.form.vehicle_available=r.vehicle_available;this.form.manual=r.transmissions.includes('MANUAL');this.form.automatic=r.transmissions.includes('AUTOMATIC');if(r.vehicle){this.form.vehicle_make=r.vehicle.make;this.form.vehicle_model=r.vehicle.model;this.form.vehicle_year=r.vehicle.year;this.form.vehicle_transmission=r.vehicle.transmission}if(r.service_area){this.form.city=r.service_area.city;this.form.uf=r.service_area.uf;this.form.region=r.service_area.region;this.form.radius_km=r.service_area.radius_km}this.form.location_authorized=r.location_authorized;this.photo=r.photo_present;this.docs=r.document_types;this.submitted=r.profile_status!=='DRAFT'}
 send(){if(!this.form.synthetic_data_confirmed){this.error='Confirme que os dados são sintéticos.';return}this.sending=true;this.http.post('/demo/instructor-onboarding/submit/',{}).subscribe({next:()=>{this.sending=false;this.submitted=true;this.cdr.markForCheck()},error:e=>{this.sending=false;this.error=e.error?.detail||'Não foi possível enviar.';this.cdr.markForCheck()}})}
}
