import { AfterViewInit,Component,ElementRef,OnDestroy,ViewChild,inject } from '@angular/core';
import { FormsModule } from '@angular/forms';import { RouterLink } from '@angular/router';import { HttpErrorResponse } from '@angular/common/http';
import { LeafletMapProvider } from '../../demo/map.provider';import { InstructorSearchProvider,SearchFilters,SearchInstructor } from '../../demo/instructor-search.provider';

@Component({selector:'app-instructor-map',imports:[FormsModule,RouterLink],template:`
<section class="page wide"><div class="demo-flag">DEMO · PostGIS real · pontos de atendimento sintéticos</div><header class="page-head"><div><p class="eyebrow">Busca geoespacial</p><h1>Encontre um instrutor perto de você</h1><p>Informe uma das cidades demonstrativas. Não solicitamos sua localização automática.</p></div></header>
<form class="map-search" (ngSubmit)="search()"><label class="location">Onde você precisa de um instrutor?<input name="location" [(ngModel)]="filters.location" placeholder="Cidade, bairro ou CEP" required></label><label>Categoria<select name="category" [(ngModel)]="filters.category"><option value="B">Categoria B</option></select></label><label>Transmissão<select name="transmission" [(ngModel)]="filters.transmission"><option value="">Manual ou automático</option><option value="MANUAL">Manual</option><option value="AUTOMATIC">Automático</option></select></label><label>Veículo<select name="vehicle" [(ngModel)]="filters.vehicleAvailable"><option [ngValue]="true">Veículo do instrutor</option></select></label><label>Raio<select name="radius" [(ngModel)]="filters.radius"><option [ngValue]="5">5 km</option><option [ngValue]="10">10 km</option><option [ngValue]="20">20 km</option><option [ngValue]="50">50 km</option></select></label><button class="button primary" type="submit" [disabled]="loading">Buscar instrutores</button></form>
@if(loading){<div class="map-state"><i class="pi pi-spin pi-spinner"></i> Buscando instrutores próximos...</div>}@else if(error){<div class="map-state error"><p>Não foi possível consultar o mapa agora.</p><button class="button ghost" (click)="search()">Tentar novamente</button></div>}@else if(searched&&!items.length){<div class="map-state"><p>Não encontramos instrutores nesse raio.</p><button class="button ghost" (click)="increaseRadius()">Aumentar raio</button><a class="button secondary" routerLink="/aluno/demanda">Publicar o que preciso</a></div>}
<div class="mobile-tabs"><button [class.active]="view==='map'" (click)="view='map'">Mapa</button><button [class.active]="view==='list'" (click)="view='list'">Lista ({{items.length}})</button></div><div class="online-map-layout"><div class="leaflet-map" [class.mobile-hidden]="view==='list'" #map></div><div class="online-results" [class.mobile-hidden]="view==='map'">@for(i of items;track i.id){<article [class.selected]="selected?.id===i.id" (click)="select(i)"><div><strong>{{i.display_name}}</strong><span><i class="pi pi-star-fill"></i> {{i.demo_rating}} · {{i.distance_km}} km</span><small>Categoria {{i.categories.join(', ')}} · {{i.transmission==='MANUAL'?'Manual':'Automático'}} · veículo disponível</small></div><b>R$ {{i.demo_price}} / aula</b><a class="button secondary" [routerLink]="['/aluno/instrutores','marina-demo']" (click)="$event.stopPropagation()">Ver perfil</a></article>}@if(selected){<div class="selected-card"><small>MARCADOR SELECIONADO · DEMO</small><h2>{{selected.display_name}}</h2><p>{{selected.distance_km}} km · Categoria {{selected.categories.join(', ')}} · {{selected.transmission==='MANUAL'?'Manual':'Automático'}}</p><strong>R$ {{selected.demo_price}} / aula</strong><a class="button primary" routerLink="/aluno/instrutores/marina-demo">Ver perfil</a></div>}</div></div><p class="map-credit">Mapa online © OpenStreetMap · coordenadas representam regiões sintéticas de atendimento.</p></section>`})
export class InstructorMapComponent implements AfterViewInit,OnDestroy{@ViewChild('map')mapElement!:ElementRef<HTMLElement>;private readonly api=inject(InstructorSearchProvider);private readonly map=inject(LeafletMapProvider);filters:SearchFilters={location:'Porto Alegre',radius:10,category:'B',transmission:'',vehicleAvailable:true};items:SearchInstructor[]=[];selected:SearchInstructor|null=null;loading=false;searched=false;error=false;view:'map'|'list'='map';ngAfterViewInit(){this.map.mount(this.mapElement.nativeElement,id=>{const item=this.items.find(x=>x.id===id);if(item)this.select(item)});this.search()}search(){this.loading=true;this.error=false;this.api.geocode(this.filters.location).subscribe({next:g=>{const point=g.results[0];this.api.search(point.latitude,point.longitude,this.filters).subscribe({next:r=>{this.items=r.results;this.selected=null;this.loading=false;this.searched=true;this.map.render(this.items,null)},error:()=>this.fail()})},error:(e:HttpErrorResponse)=>{this.items=[];this.loading=false;this.searched=true;this.error=e.status!==404;this.map.render([],null)}})}select(item:SearchInstructor){this.selected=item;this.map.select(item.id)}increaseRadius(){this.filters.radius=this.filters.radius===50?50:Math.min(50,this.filters.radius*2);this.search()}private fail(){this.loading=false;this.error=true;this.searched=true}ngOnDestroy(){this.map.destroy()}}
