import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

@Component({
  selector:'app-instructor-onboarding', imports:[FormsModule,RouterLink],
  template:`<section class="page narrow onboarding"><div class="demo-flag">DEMO · somente dados sintéticos</div><header class="page-head"><div><p class="eyebrow">Quero atuar como instrutor</p><h1>Crie seu cadastro demonstrativo</h1><p>O envio não significa aprovação nem publicação.</p></div></header><ol class="steps">@for(label of labels;track label;let i=$index){<li [class.active]="step===i+1" [class.done]="step>i+1"><b>{{i+1}}</b><span>{{label}}</span></li>}</ol>
  @if(!submitted){<form class="card" (ngSubmit)="send()">
  @if(step===1){<h2>1. Dados</h2><label>Nome demonstrativo<input name="name" [(ngModel)]="form.display_name" required></label><label>E-mail sintético<input name="email" type="email" [(ngModel)]="form.email" required></label><label>Senha DEMO<input name="password" type="password" minlength="10" [(ngModel)]="form.password" required></label>}
  @if(step===2){<h2>2. Atendimento</h2><div class="two"><label>Categoria<select name="category" [(ngModel)]="form.category"><option value="B">B</option></select></label><label>Raio<select name="radius" [(ngModel)]="form.radius_km"><option [ngValue]="5">5 km</option><option [ngValue]="10">10 km</option><option [ngValue]="20">20 km</option><option [ngValue]="50">50 km</option></select></label></div><label class="check"><input type="checkbox" name="vehicle" [(ngModel)]="form.vehicle_available"> Possui veículo</label><fieldset><legend>Transmissão</legend><label class="check"><input type="checkbox" name="manual" [(ngModel)]="form.manual"> Manual</label><label class="check"><input type="checkbox" name="automatic" [(ngModel)]="form.automatic"> Automática</label></fieldset>}
  @if(step===3){<h2>3. Veículo</h2>@if(form.vehicle_available){<div class="two"><label>Marca<input name="make" [(ngModel)]="form.vehicle_make"></label><label>Modelo<input name="model" [(ngModel)]="form.vehicle_model"></label><label>Ano<input name="year" type="number" [(ngModel)]="form.vehicle_year"></label><label>Transmissão<select name="vt" [(ngModel)]="form.vehicle_transmission"><option value="MANUAL">Manual</option><option value="AUTOMATIC">Automática</option></select></label></div><p>Nenhuma placa é solicitada ou publicada.</p>}@else{<p>Sem veículo informado.</p>}}
  @if(step===4){<h2>4. Localização de atendimento</h2><div class="two"><label>Cidade<input name="city" [(ngModel)]="form.city"></label><label>UF<select name="uf" [(ngModel)]="form.uf" (ngModelChange)="form.credential_uf=$event"><option>RS</option><option>SC</option><option>SP</option><option>RJ</option><option>ES</option></select></label></div><label>Região/bairro opcional<input name="region" [(ngModel)]="form.region"></label><p>Raio: {{form.radius_km}} km. Não informe endereço residencial.</p><label class="check"><input type="checkbox" name="location" [(ngModel)]="form.location_authorized"> Autorizo o uso da área de atendimento na descoberta.</label>}
  @if(step===5){<h2>5. Documentos e credenciais</h2><div class="info">Somente fixtures sintéticas PDF, PNG ou JPEG de até 5 MB. O nome deve começar por <b>fixture-</b>. Não envie CNH, CPF, placa, documento ou dado real.</div><div class="two"><label>Tipo<select name="credential" [(ngModel)]="form.credential_type"><option value="CREDENCIAL_DEMO">Credencial demonstrativa</option></select></label><label>UF<select name="credentialUf" [(ngModel)]="form.credential_uf"><option>RS</option><option>SC</option><option>SP</option><option>RJ</option><option>ES</option></select></label></div><label>Validade demonstrativa<input name="validity" [(ngModel)]="form.credential_validity"></label><label>Credencial sintética<input type="file" accept=".pdf,.png,.jpg,.jpeg" (change)="chooseFile('credential_file',$event)"></label><label>Curso sintético (opcional)<input type="file" accept=".pdf,.png,.jpg,.jpeg" (change)="chooseFile('course_file',$event)"></label>@if(form.vehicle_available){<label>Evidência sintética do veículo (opcional)<input type="file" accept=".pdf,.png,.jpg,.jpeg" (change)="chooseFile('vehicle_file',$event)"></label>}<p>Os arquivos ficam privados e pendentes de revisão; nada é publicado automaticamente.</p>}
  @if(step===6){<h2>6. Revisão</h2><dl><dt>Nome</dt><dd>{{form.display_name}}</dd><dt>Conta</dt><dd>{{form.email}}</dd><dt>Atendimento</dt><dd>{{form.city}}/{{form.uf}} · {{form.radius_km}} km</dd><dt>Veículo</dt><dd>{{form.vehicle_available?form.vehicle_make+' '+form.vehicle_model:'Sem veículo'}}</dd><dt>Status</dt><dd>Será enviado para análise</dd></dl><label class="check"><input type="checkbox" name="synthetic" [(ngModel)]="form.synthetic_data_confirmed"> Confirmo que todos os dados são sintéticos.</label>}
  @if(error){<p class="error">{{error}}</p>}<footer><button type="button" class="button ghost" [disabled]="step===1||sending" (click)="step=step-1">Voltar</button>@if(step<6){<button type="button" class="button primary" (click)="next()">Continuar</button>}@else{<button class="button primary" [disabled]="sending">{{sending?'Enviando…':'Enviar para análise'}}</button>}</footer></form>}
  @else{<article class="submitted"><i class="pi pi-check-circle"></i><h2>Perfil enviado para análise</h2><p>{{responseName}} foi salvo no banco e não foi publicado automaticamente.</p><ol><li>✓ Cadastro criado</li><li>✓ Perfil preenchido</li><li>✓ Enviado para análise</li><li>○ Verificação</li><li>○ Aprovação</li><li>○ Publicação</li></ol><a class="button secondary" routerLink="/entrar">Entrar com meu cadastro</a></article>}</section>`,
  styles:[`.steps{display:grid;grid-template-columns:repeat(6,1fr);gap:.4rem;padding:0;list-style:none}.steps li{display:flex;gap:.35rem;align-items:center;color:#71858b;font-size:.72rem}.steps b{display:grid;place-items:center;width:2rem;aspect-ratio:1;border-radius:50%;background:#dfeae8}.steps .active b,.steps .done b{color:#fff;background:#138f8d}.card,.submitted{padding:1.5rem;border:1px solid #d6e5e3;border-radius:1.2rem;background:#fff}.card label{display:flex;flex-direction:column;gap:.4rem;margin:1rem 0;font-weight:750}.card input,.card select{min-height:3rem;padding:.7rem;border:1px solid #bfd5d2;border-radius:.7rem}.two{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.check{flex-direction:row!important;align-items:center!important}.check input{min-height:auto}.card footer{display:flex;justify-content:space-between;margin-top:1.5rem}.card dl{display:grid;grid-template-columns:7rem 1fr;gap:.6rem}.card dd{margin:0}.error{color:#9a302c}.submitted{text-align:center}.submitted>i{font-size:4rem;color:#159985}.submitted ol{display:grid;gap:.6rem;max-width:20rem;margin:1rem auto;text-align:left;list-style:none}@media(max-width:650px){.steps span{display:none}.steps{justify-items:center}.two{grid-template-columns:1fr}}`]
})
export class InstructorOnboardingComponent {
  private http=inject(HttpClient);step=1;sending=false;submitted=false;error='';responseName='';readonly labels=['Dados','Atendimento','Veículo','Localização','Documentos','Revisão'];
  form={email:'instrutor@example.invalid',password:'DemoSeguro123!',prerequisite_accepted:true,display_name:'Alex Demo',city:'Porto Alegre',uf:'RS',region:'Centro',category:'B',vehicle_available:true,vehicle_make:'Marca Demo',vehicle_model:'Modelo Demo',vehicle_year:2024,vehicle_transmission:'MANUAL',manual:true,automatic:false,radius_km:10,location_authorized:false,credential_type:'CREDENCIAL_DEMO',credential_uf:'RS',credential_validity:'12/2027',synthetic_data_confirmed:false};
  files:Record<string,File|undefined>={};
  chooseFile(field:string,event:Event){const file=(event.target as HTMLInputElement).files?.[0];this.files[field]=file;if(file&&!file.name.toLowerCase().startsWith('fixture-'))this.error='O nome da fixture deve começar por fixture-.';else this.error=''}
  next(){if(this.valid())this.step++;else this.error='Preencha os campos obrigatórios usando somente dados sintéticos.'}
  valid(){this.error='';if(this.step===1)return this.form.display_name.length>1&&this.form.email.endsWith('@example.invalid')&&this.form.password.length>=10;if(this.step===2)return this.form.manual||this.form.automatic;if(this.step===3)return !this.form.vehicle_available||!!(this.form.vehicle_make&&this.form.vehicle_model&&this.form.vehicle_year);if(this.step===4)return !!this.form.city&&this.form.location_authorized;if(this.step===5)return !!this.form.credential_validity&&this.form.credential_uf===this.form.uf;return true}
  send(){if(!this.form.synthetic_data_confirmed||!this.valid()){this.error='Confirme que todos os dados são sintéticos.';return}if(Object.values(this.files).some(file=>file&&!file.name.toLowerCase().startsWith('fixture-'))){this.error='Todos os arquivos devem ser fixtures sintéticas prefixadas por fixture-.';return}const points:Record<string,[number,number]>={RS:[-30.0346,-51.2177],SC:[-27.5949,-48.5482],SP:[-23.5505,-46.6333],RJ:[-22.9068,-43.1729],ES:[-20.3155,-40.3128]};const [latitude,longitude]=points[this.form.uf];const payload=new FormData();const data:any={...this.form,transmissions:[this.form.manual?'MANUAL':null,this.form.automatic?'AUTOMATIC':null].filter(Boolean),latitude,longitude};Object.entries(data).forEach(([key,value])=>{if(Array.isArray(value))value.forEach(item=>payload.append(key,String(item)));else payload.append(key,String(value))});Object.entries(this.files).forEach(([key,file])=>{if(file)payload.append(key,file)});this.sending=true;this.http.post<{display_name:string}>('/demo/instructor-onboarding/',payload).subscribe({next:r=>{this.responseName=r.display_name;this.submitted=true;this.sending=false},error:e=>{this.error=e.error?.detail||'Não foi possível enviar. Confira a fixture e se o e-mail sintético ainda não foi usado.';this.sending=false}})}
}
