import { Component, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

type DemoForm={display_name:string;city:string;uf:string;category:string;vehicle_available:boolean;manual:boolean;automatic:boolean;radius_km:number;location_authorized:boolean;credential_type:string;credential_uf:string;credential_validity:string;synthetic_data_confirmed:boolean};
@Component({selector:'app-instructor-onboarding',imports:[FormsModule,RouterLink],template:`
<section class="page narrow onboarding"><div class="demo-flag">DEMO · somente dados sintéticos</div>
<header class="page-head"><div><p class="eyebrow">Quero atuar como instrutor</p><h1>Apresente seu perfil demonstrativo</h1><p>Esta solicitação é para participação no InstrutorPro. Não concede autorização oficial para atividade regulamentada.</p></div></header>
<ol class="onboarding-steps">@for(label of labels;track label;let i=$index){<li [class.active]="step===i+1" [class.done]="step>i+1"><b>{{i+1}}</b><span>{{label}}</span></li>}</ol>
@if(!submitted){<form class="onboarding-card" #wizard="ngForm" (ngSubmit)="send()">
@if(step===1){<h2>1. Dados básicos</h2><label>Nome demonstrativo<input name="name" [(ngModel)]="form.display_name" required minlength="2" placeholder="Ex.: Alex Demo"></label><div class="two"><label>Cidade<input name="city" [(ngModel)]="form.city" required placeholder="Porto Alegre"></label><label>UF<select name="uf" [(ngModel)]="form.uf" (ngModelChange)="form.credential_uf=$event"><option>RS</option><option>SC</option><option>SP</option><option>RJ</option><option>ES</option></select></label></div>}
@if(step===2){<h2>2. Como você atende?</h2><div class="two"><label>Categoria<select name="category" [(ngModel)]="form.category"><option value="B">Categoria B</option></select></label><label>Raio<select name="radius" [(ngModel)]="form.radius_km"><option [ngValue]="5">5 km</option><option [ngValue]="10">10 km</option><option [ngValue]="20">20 km</option><option [ngValue]="50">50 km</option></select></label></div><label class="check"><input type="checkbox" name="vehicle" [(ngModel)]="form.vehicle_available"> Veículo próprio/disponível</label><fieldset><legend>Transmissão</legend><label class="check"><input type="checkbox" name="manual" [(ngModel)]="form.manual"> Manual</label><label class="check"><input type="checkbox" name="automatic" [(ngModel)]="form.automatic"> Automático</label></fieldset>}
@if(step===3){<h2>3. Área de atendimento</h2><p><strong>{{form.city}}, {{form.uf}}</strong> · ponto demonstrativo da região · raio de {{form.radius_km}} km.</p><div class="location-demo"><i class="pi pi-map-marker"></i><span>O ponto representa uma região de atendimento sintética. Não informe residência.</span></div><label class="consent"><input type="checkbox" name="consent" [(ngModel)]="form.location_authorized" required> Autorizo o uso desta localização de <strong>atendimento</strong> na descoberta do InstrutorPro, conforme termo DEMO-ONBOARDING-1.</label>}
@if(step===4){<h2>4. Credenciais</h2><div class="info"><i class="pi pi-info-circle"></i><span>Estrutura apenas visual. Não informe CNH, CPF, número oficial nem envie documento.</span></div><div class="two"><label>Tipo<select name="credential" [(ngModel)]="form.credential_type"><option value="CREDENCIAL_DEMO">Credencial demonstrativa</option></select></label><label>UF<select name="credentialUf" [(ngModel)]="form.credential_uf"><option>RS</option><option>SC</option><option>SP</option><option>RJ</option><option>ES</option></select></label></div><label>Validade demonstrativa<input name="validity" [(ngModel)]="form.credential_validity" placeholder="12/2027" required></label>}
@if(step===5){<h2>5. Revisão</h2><dl><dt>Nome</dt><dd>{{form.display_name}}</dd><dt>Atendimento</dt><dd>{{form.city}}/{{form.uf}} · categoria B · {{form.radius_km}} km</dd><dt>Transmissão</dt><dd>{{form.manual?'Manual ':''}}{{form.automatic?'Automático':''}}</dd><dt>Localização</dt><dd>{{form.location_authorized?'Autorizada para descoberta':'Não autorizada'}}</dd><dt>Credencial</dt><dd>Demonstrativa · {{form.credential_uf}} · {{form.credential_validity}}</dd></dl><label class="consent"><input type="checkbox" name="synthetic" [(ngModel)]="form.synthetic_data_confirmed" required> Confirmo que todas as informações desta demonstração são sintéticas.</label>}
@if(error){<p class="form-error">{{error}}</p>}<footer><button type="button" class="button ghost" [disabled]="step===1||sending" (click)="step=step-1">Voltar</button>@if(step<5){<button type="button" class="button primary" (click)="next()">Continuar</button>}@else{<button type="submit" class="button primary" [disabled]="sending">{{sending?'Enviando...':'Enviar para análise'}}</button>}</footer></form>}
@else{<article class="submitted"><i class="pi pi-check-circle"></i><p class="eyebrow">Solicitação DEMO recebida</p><h2>Perfil enviado para análise</h2><p>{{responseName}} não foi publicado automaticamente.</p><ol><li class="done">✓ Cadastro preenchido</li><li class="done">✓ Enviado para análise</li><li>○ Verificação</li><li>○ Aprovação</li><li>○ Publicação</li></ol><a class="button secondary" routerLink="/profissional">Voltar à área profissional</a></article>}</section>`,styles:[`
.onboarding-steps{display:grid;grid-template-columns:repeat(5,1fr);gap:.5rem;padding:0;list-style:none}.onboarding-steps li{display:flex;align-items:center;gap:.4rem;color:#748890;font-size:.75rem}.onboarding-steps b{display:grid;place-items:center;width:2rem;aspect-ratio:1;border-radius:50%;background:#dfeae8}.onboarding-steps .active b,.onboarding-steps .done b{color:#fff;background:#138f8d}.onboarding-card,.submitted{margin-top:1.5rem;padding:clamp(1.2rem,4vw,2rem);border:1px solid #d6e5e3;border-radius:1.4rem;background:#fff}.onboarding-card label{display:flex;flex-direction:column;gap:.45rem;margin:1rem 0;font-weight:750}.onboarding-card input,.onboarding-card select{min-height:3rem;padding:.7rem;border:1px solid #c7dcda;border-radius:.7rem}.two{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.check,.consent{flex-direction:row!important;align-items:flex-start!important}.check input,.consent input{min-height:auto}.location-demo{display:flex;gap:1rem;padding:1rem;border-radius:1rem;background:#e9f5f2}.location-demo i{font-size:2rem}.onboarding-card footer{display:flex;justify-content:space-between;margin-top:2rem}.onboarding-card fieldset{border:1px solid #d6e5e3;border-radius:1rem}.onboarding-card dl{display:grid;grid-template-columns:8rem 1fr;gap:.7rem}.onboarding-card dt{font-weight:800}.onboarding-card dd{margin:0}.form-error{color:#9a302c}.submitted{text-align:center}.submitted>i{color:#159985;font-size:4rem}.submitted ol{display:grid;gap:.7rem;max-width:20rem;margin:2rem auto;text-align:left;list-style:none}.submitted li.done{color:#147f72;font-weight:800}@media(max-width:650px){.onboarding-steps span{display:none}.onboarding-steps{justify-items:center}.two{grid-template-columns:1fr}}
`]})
export class InstructorOnboardingComponent{
 private http=inject(HttpClient);step=1;sending=false;submitted=false;error='';responseName='';readonly labels=['Dados','Atendimento','Localização','Credenciais','Revisão'];
 form:DemoForm={display_name:'Alex Demo',city:'Porto Alegre',uf:'RS',category:'B',vehicle_available:true,manual:true,automatic:false,radius_km:10,location_authorized:false,credential_type:'CREDENCIAL_DEMO',credential_uf:'RS',credential_validity:'12/2027',synthetic_data_confirmed:false};
 next(){if(this.validStep())this.step++;else this.error='Preencha os campos obrigatórios desta etapa com dados sintéticos.'}
 validStep(){this.error='';if(this.step===1)return this.form.display_name.trim().length>=2&&!!this.form.city.trim();if(this.step===2)return this.form.manual||this.form.automatic;if(this.step===3)return this.form.location_authorized;if(this.step===4)return !!this.form.credential_validity&&this.form.credential_uf===this.form.uf;return true}
 send(){if(!this.form.synthetic_data_confirmed||!this.validStep()){this.error='Confirme que todos os dados são sintéticos.';return}const points:Record<string,[number,number]>={RS:[-30.0346,-51.2177],SC:[-27.5949,-48.5482],SP:[-23.5505,-46.6333],RJ:[-22.9068,-43.1729],ES:[-20.3155,-40.3128]};const [latitude,longitude]=points[this.form.uf];this.sending=true;this.http.post<{display_name:string}>('/demo/instructor-onboarding/',{...this.form,transmissions:[this.form.manual?'MANUAL':null,this.form.automatic?'AUTOMATIC':null].filter(Boolean),latitude,longitude}).subscribe({next:r=>{this.responseName=r.display_name;this.submitted=true;this.sending=false},error:()=>{this.error='Não foi possível enviar a demonstração. Revise os dados e tente novamente.';this.sending=false}})}
}
