# Generated by Django 5.2.17 on 2026-08-24 04:39

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoInstructorServiceLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fixture_key', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('public_service_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('private_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('categories', models.JSONField(default=list)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automático')], max_length=12)),
                ('vehicle_available', models.BooleanField(default=True)),
                ('demo_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('demo_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability_summary', models.CharField(max_length=160)),
                ('is_demo', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['uf', 'city'], name='discovery_d_uf_e6077c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_demo', True)), name='discovery_demo_rows_only')],
            },
        ),
    ]
