# Generated by Django 5.2.17 on 2026-08-24 05:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
        ('people', '0002_role_assignment_history_and_authorization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('categories', models.JSONField(default=list)),
                ('transmission_options', models.JSONField(default=list)),
                ('vehicle_available', models.BooleanField(default=True)),
                ('service_radius_km', models.PositiveSmallIntegerField(default=10)),
                ('demo_rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=2)),
                ('demo_price', models.DecimalField(decimal_places=2, default=90, max_digits=8)),
                ('availability_summary', models.CharField(default='Horários demonstrativos nesta semana', max_length=160)),
                ('profile_status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado'), ('UNDER_REVIEW', 'Em revisão'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('SUSPENDED', 'Suspenso')], default='DRAFT', max_length=20)),
                ('verification_status', models.CharField(choices=[('NOT_STARTED', 'Não iniciada'), ('PENDING', 'Pendente'), ('VERIFIED', 'Verificada'), ('REJECTED', 'Rejeitada'), ('EXPIRED', 'Expirada'), ('REVOKED', 'Revogada')], default='NOT_STARTED', max_length=20)),
                ('verified_until', models.DateTimeField(blank=True, null=True)),
                ('publication_status', models.CharField(choices=[('UNPUBLISHED', 'Não publicado'), ('APPROVED', 'Publicado'), ('REJECTED', 'Rejeitado'), ('SUSPENDED', 'Suspenso')], default='UNPUBLISHED', max_length=20)),
                ('is_demo', models.BooleanField(default=True, editable=False)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profile', to='people.person')),
            ],
            options={
                'permissions': [('manage_instructor_publication', 'Can decide instructor publication')],
            },
        ),
        migrations.CreateModel(
            name='InstructorServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('public_service_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('private_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('radius_km', models.PositiveSmallIntegerField(default=10)),
                ('location_authorized', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_area', to='discovery.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LocationPublicationAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=160)),
                ('policy_version', models.CharField(max_length=40)),
                ('authorized_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_authorizations', to=settings.AUTH_USER_MODEL)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorization_history', to='discovery.instructorservicearea')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='SYNTHETIC', max_length=30)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Não iniciada'), ('PENDING', 'Pendente'), ('VERIFIED', 'Verificada'), ('REJECTED', 'Rejeitada'), ('EXPIRED', 'Expirada'), ('REVOKED', 'Revogada')], max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_verifications', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_history', to='discovery.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVE', 'Aprovar'), ('REJECT', 'Rejeitar'), ('SUSPEND', 'Suspender'), ('UNPUBLISH', 'Despublicar')], max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_decisions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_history', to='discovery.instructorprofile')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='discovery.professionalverification')),
            ],
        ),
    ]
