# Generated by Django 5.2.17 on 2026-08-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_instructorprofile_instructorservicearea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorprofile',
            options={'permissions': [('manage_instructor_publication', 'Can decide instructor publication')], 'verbose_name': 'perfil de instrutor', 'verbose_name_plural': 'perfis de instrutores'},
        ),
        migrations.AlterModelOptions(
            name='instructorservicearea',
            options={'verbose_name': 'área de atendimento do instrutor', 'verbose_name_plural': 'áreas de atendimento dos instrutores'},
        ),
        migrations.AlterModelOptions(
            name='locationpublicationauthorization',
            options={'verbose_name': 'autorização de publicação da localização', 'verbose_name_plural': 'autorizações de publicação da localização'},
        ),
        migrations.AlterModelOptions(
            name='professionalverification',
            options={'verbose_name': 'verificação profissional', 'verbose_name_plural': 'verificações profissionais'},
        ),
        migrations.AlterModelOptions(
            name='publicationdecision',
            options={'verbose_name': 'decisão de publicação', 'verbose_name_plural': 'decisões de publicação'},
        ),
    ]
