# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0007_professional_verification_request"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demoinstructorservicelocation",
            options={
                "ordering": ["display_name"],
                "verbose_name": "local de atendimento demonstrativo",
                "verbose_name_plural": "locais de atendimento demonstrativos",
            },
        ),
        migrations.AlterModelOptions(
            name="instructorprofile",
            options={
                "permissions": [
                    ("manage_instructor_publication", "Pode decidir a publicação de instrutores")
                ],
                "verbose_name": "perfil de instrutor",
                "verbose_name_plural": "perfis de instrutores",
            },
        ),
        migrations.AlterModelOptions(
            name="professionalverificationrequest",
            options={
                "ordering": ["submitted_at", "created_at"],
                "permissions": [
                    ("review_professional_verification", "Pode revisar verificação profissional"),
                    ("reveal_protected_identifier", "Pode revelar identificador pessoal protegido"),
                ],
                "verbose_name": "solicitação de verificação profissional",
                "verbose_name_plural": "solicitações de verificação profissional",
            },
        ),
    ]
