# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_auditevent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={
                "ordering": ["-occurred_at"],
                "permissions": [
                    ("view_security_audit", "Pode visualizar eventos de auditoria de segurança")
                ],
                "verbose_name": "evento de auditoria",
                "verbose_name_plural": "eventos de auditoria",
            },
        ),
    ]
