# Generated by Django 5.2.17 on 2026-09-17 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_privacy_notice(apps, schema_editor):
    PrivacyNotice = apps.get_model("privacy", "PrivacyNotice")
    PrivacyNotice.objects.create(
        version="2026-09-16",
        title="Política de Privacidade e Proteção de Dados",
        published_at="2026-09-16T00:00:00-03:00",
        is_current=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uq_current_privacy_notice')],
            },
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Acesso'), ('CORRECTION', 'Correção'), ('DELETION', 'Exclusão'), ('PORTABILITY', 'Portabilidade'), ('CONSENT_REVOCATION', 'Revogação de consentimento'), ('OTHER', 'Outro')], max_length=24)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('IN_REVIEW', 'Em análise'), ('COMPLETED', 'Concluída'), ('REJECTED', 'Não atendida integralmente')], default='OPEN', max_length=16)),
                ('details', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'permissions': [('manage_privacy_requests', 'Can manage privacy requests')],
            },
        ),
        migrations.RunPython(seed_privacy_notice, migrations.RunPython.noop),
    ]
