# Generated by Django 5.2.17 on 2026-09-17 09:09
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(choices=[("TERMS", "Termos de Uso")], max_length=20),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("STUDENT", "Aluno"), ("INSTRUCTOR", "Instrutor")], max_length=20
                    ),
                ),
                ("version", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(editable=False, max_length=64)),
                ("effective_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "audience", "version"),
                        name="uq_legal_document_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("document_type", "audience"),
                        name="uq_active_legal_document_audience",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalAcceptanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "privacy_notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_acceptances",
                        to="privacy.privacynotice",
                    ),
                ),
                (
                    "terms_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="privacy.legaldocument",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "terms_document", "privacy_notice"),
                        name="uq_account_legal_acceptance_versions",
                    )
                ],
            },
        ),
    ]
