# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0003_seed_terms_v1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalacceptancerecord",
            options={
                "verbose_name": "registro de aceite legal",
                "verbose_name_plural": "registros de aceite legal",
            },
        ),
        migrations.AlterModelOptions(
            name="legaldocument",
            options={"verbose_name": "documento legal", "verbose_name_plural": "documentos legais"},
        ),
        migrations.AlterModelOptions(
            name="privacynotice",
            options={
                "verbose_name": "aviso de privacidade",
                "verbose_name_plural": "avisos de privacidade",
            },
        ),
        migrations.AlterModelOptions(
            name="privacyrequest",
            options={
                "ordering": ["-requested_at"],
                "permissions": [
                    ("manage_privacy_requests", "Pode gerenciar solicitações de privacidade")
                ],
                "verbose_name": "solicitação de privacidade",
                "verbose_name_plural": "solicitações de privacidade",
            },
        ),
    ]
