# Generated by Django 5.2.17 on 2026-08-24 03:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_inactive_accounts(apps, schema_editor):
    account = apps.get_model("accounts", "Account")
    account.objects.filter(is_active=False).update(
        lifecycle_status="DEACTIVATED",
        lifecycle_reason="LEGACY_INACTIVE",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_alter_account_date_joined_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('manage_account_lifecycle', 'Can manage account lifecycle')]},
        ),
        migrations.AddField(
            model_name='account',
            name='lifecycle_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='lifecycle_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_lifecycle_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='lifecycle_reason',
            field=models.CharField(default='ACCOUNT_CREATED', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='lifecycle_status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('BLOCKED', 'Bloqueada'), ('DEACTIVATED', 'Desativada')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='lifecycle_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(preserve_inactive_accounts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('lifecycle_status', 'ACTIVE')), models.Q(('is_active', False), ('lifecycle_status__in', ['BLOCKED', 'DEACTIVATED'])), _connector='OR'), name='account_lifecycle_matches_is_active'),
        ),
    ]
