# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_options_account_lifecycle_changed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "permissions": [
                    ("manage_account_lifecycle", "Pode gerenciar o ciclo de vida de contas")
                ],
                "verbose_name": "conta",
                "verbose_name_plural": "contas",
            },
        ),
        migrations.AlterModelOptions(
            name="externalidentity",
            options={
                "verbose_name": "identidade externa",
                "verbose_name_plural": "identidades externas",
            },
        ),
    ]
