import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';

@Component({
  selector: 'app-home', imports: [RouterLink, FormsModule], styleUrl: './home.component.scss',
  template: `<section class="landing"><div class="hero-copy"><p class="kicker">InstrutorProCNH</p><h1>O que você procura?</h1><p class="lead">Encontre instrutores próximos de você para sua CNH.</p><div class="hero-actions"><a class="button primary" routerLink="/aluno/instrutores/mapa">Quero encontrar um instrutor</a><a class="button secondary" routerLink="/profissional/instrutor/entrada">Sou instrutor</a></div><form class="search" (ngSubmit)="search()"><label for="place">Encontre instrutores perto de você</label><div><i class="pi pi-map-marker"></i><input id="place" name="place" [(ngModel)]="place" autocomplete="postal-code" placeholder="Cidade, bairro ou CEP" required><button class="button primary" type="submit"><i class="pi pi-search"></i> Buscar</button></div></form><button class="button ghost" type="button" (click)="useLocation()"><i class="pi pi-crosshairs"></i> Usar minha localização</button><p class="privacy"><i class="pi pi-lock"></i> A localização só é solicitada após seu clique e não é publicada.</p>@if(locationError){<p class="location-error" role="alert">{{locationError}}</p>}</div><div class="hero-visual" aria-label="Busca de instrutores por área de atendimento"><span class="orbit one"></span><span class="orbit two"></span><div class="road-card"><i class="pi pi-car"></i><strong>Profissionais perto de você</strong><span>sem publicar endereço residencial</span></div><div class="float-card top"><i class="pi pi-verified"></i> Credenciamento verificado</div><div class="float-card bottom"><i class="pi pi-map-marker"></i> Área de atendimento</div></div></section><section id="como-funciona" class="promise"><article><i class="pi pi-search"></i><h2>Pesquise sua região</h2><p>Informe cidade, bairro ou CEP sem precisar criar conta.</p></article><article><i class="pi pi-users"></i><h2>Compare profissionais</h2><p>Consulte perfil, veículo, categorias, preço e verificações aprovadas.</p></article><article><i class="pi pi-whatsapp"></i><h2>Converse pelo WhatsApp</h2><p>Abra o contato profissional e decida se deseja enviar a mensagem.</p></article></section>`,
})
export class HomeComponent {
  place = ''; locationError = '';
  constructor(private readonly router: Router) {}
  search() { const value = this.place.trim(); if (value) void this.router.navigate(['/aluno/instrutores/mapa'], { queryParams: { local: value } }); }
  useLocation() { this.locationError = ''; if (!navigator.geolocation) { this.locationError = 'Seu navegador não oferece geolocalização.'; return; } navigator.geolocation.getCurrentPosition(({ coords }) => void this.router.navigate(['/aluno/instrutores/mapa'], { queryParams: { latitude: coords.latitude, longitude: coords.longitude, source: 'user' } }), () => this.locationError = 'Não foi possível acessar sua localização. Pesquise por cidade, bairro ou CEP.', { enableHighAccuracy: false, timeout: 10000, maximumAge: 300000 }); }
}
