# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentcustomer",
            options={
                "verbose_name": "cliente de pagamento",
                "verbose_name_plural": "clientes de pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentorder",
            options={
                "verbose_name": "ordem de pagamento",
                "verbose_name_plural": "ordens de pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "verbose_name": "transação de pagamento",
                "verbose_name_plural": "transações de pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentwebhookevent",
            options={
                "verbose_name": "evento de webhook de pagamento",
                "verbose_name_plural": "eventos de webhook de pagamento",
            },
        ),
    ]
