# Generated by Django 5.2.17 on 2026-09-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_role_assignment_history_and_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
