# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_person_protected_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "pessoa", "verbose_name_plural": "pessoas"},
        ),
        migrations.AlterModelOptions(
            name="roleassignment",
            options={
                "permissions": [
                    ("manage_role_assignments", "Pode conceder e revogar papéis pessoais")
                ],
                "verbose_name": "atribuição de papel",
                "verbose_name_plural": "atribuições de papéis",
            },
        ),
    ]
