import { HttpClient } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';

export type SaasSummary = {
  display_name: string;
  profile_status: string;
  publication_status: string;
  plan: {code:string; name:string; entitlements:string[]};
  metrics: {days:number; search_impressions:number; profile_views:number; whatsapp_contacts:number; conversion_percent:number; timeline:{date:string;impressions:number;views:number;contacts:number}[]};
};

@Component({selector:'app-professional-nav',imports:[RouterLink],template:`<nav class="pro-nav" aria-label="Menu profissional"><a routerLink="/instrutor">Visão geral</a><a routerLink="/profissional/instrutor/status">Meu perfil</a><a routerLink="/instrutor/desempenho">Desempenho</a><a routerLink="/instrutor/plano">Meu plano</a></nav>`,styles:[`.pro-nav{display:flex;gap:.6rem;overflow:auto;margin-bottom:1rem}.pro-nav a{white-space:nowrap;padding:.65rem .85rem;border-radius:999px;background:#e8f4f2;color:#084e62;font-weight:700}`]})
export class ProfessionalNavComponent {}

@Component({selector:'app-instructor-saas-dashboard',imports:[RouterLink,ProfessionalNavComponent],template:`<section class="page wide"><app-professional-nav/>@if(data();as d){<header class="page-head"><div><p class="eyebrow">InstrutorProCNH</p><h1>Olá, {{d.display_name}}</h1><p>Seu perfil: <strong>{{status(d)}}</strong></p></div><div><strong>Plano {{d.plan.name}}</strong><br><a routerLink="/instrutor/plano">Ver meu plano</a></div></header><h2>Últimos 30 dias</h2><div class="metrics"><article><strong>{{d.metrics.search_impressions}}</strong><span>Aparições nas buscas</span></article><article><strong>{{d.metrics.profile_views}}</strong><span>Visitas ao perfil</span></article><article><strong>{{d.metrics.whatsapp_contacts}}</strong><span>Contatos pelo WhatsApp</span></article></div>@if(!d.metrics.whatsapp_contacts){<article class="zero"><h2>Seu perfil ainda não recebeu contatos neste período.</h2><p>Mantenha seu perfil completo, preço atualizado e área de atendimento correta para aparecer nas buscas elegíveis.</p></article>}<div class="actions"><a class="button primary" routerLink="/instrutor/desempenho">Ver desempenho</a><a class="button secondary" routerLink="/instrutor/plano">Meu plano</a></div>}@else{<p>Carregando seu painel…</p>}</section>`,styles:[`.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.metrics article,.zero{padding:1.3rem;border:1px solid #d6e5e3;border-radius:1rem;background:#fff}.metrics strong{display:block;font-size:2rem;color:#0c807e}.metrics span{font-weight:700}.actions{display:flex;gap:.8rem;margin-top:1rem}@media(max-width:650px){.metrics{grid-template-columns:1fr}.actions{display:grid}}`]})
export class InstructorSaasDashboardComponent {private http=inject(HttpClient);data=signal<SaasSummary|undefined>(undefined);constructor(){this.http.get<SaasSummary>('/marketplace/instructor/saas-summary/?days=30').subscribe(v=>this.data.set(v))}status(d:SaasSummary){return d.publication_status==='APPROVED'?'Publicado':d.publication_status==='SUSPENDED'?'Suspenso':d.profile_status==='DRAFT'?'Incompleto':'Em análise'}}

@Component({selector:'app-instructor-performance',imports:[ProfessionalNavComponent],template:`<section class="page wide"><app-professional-nav/><header class="page-head"><div><p class="eyebrow">Seu desempenho</p><h1>Resultados do perfil</h1><p>Contatos representam cliques para iniciar uma conversa, não vendas.</p></div></header><div class="periods">@for(p of periods;track p){<button [class.active]="days()===p" (click)="load(p)">{{p}} dias</button>}</div>@if(data();as d){<div class="metrics"><article><strong>{{d.metrics.search_impressions}}</strong><span>Aparições</span></article><article><strong>{{d.metrics.profile_views}}</strong><span>Visitas</span></article><article><strong>{{d.metrics.whatsapp_contacts}}</strong><span>Contatos</span></article><article><strong>{{d.metrics.conversion_percent}}%</strong><span>Perfil → WhatsApp</span></article></div><h2>Tendência temporal</h2><div class="trend">@for(row of d.metrics.timeline;track row.date){<div><time>{{row.date}}</time><span>Aparições {{row.impressions}}</span><span>Visitas {{row.views}}</span><span>Contatos {{row.contacts}}</span></div>}@empty{<p>Seu perfil ainda não recebeu contatos neste período.</p>}</div>}</section>`,styles:[`.periods{display:flex;gap:.5rem;margin-bottom:1rem}.periods button{padding:.7rem 1rem;border:1px solid #bad4d1;border-radius:999px;background:#fff}.periods .active{background:#087f7d;color:#fff}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem}.metrics article,.trend{padding:1.2rem;border:1px solid #d6e5e3;border-radius:1rem;background:#fff}.metrics strong{display:block;font-size:2rem;color:#0c807e}.trend div{display:grid;grid-template-columns:1.2fr repeat(3,1fr);gap:.6rem;padding:.6rem;border-bottom:1px solid #edf3f2}@media(max-width:700px){.metrics{grid-template-columns:1fr 1fr}.trend div{grid-template-columns:1fr}}`]})
export class InstructorPerformanceComponent {private http=inject(HttpClient);data=signal<SaasSummary|undefined>(undefined);days=signal(30);periods=[7,30,90];constructor(){this.load(30)}load(days:number){this.days.set(days);this.http.get<SaasSummary>(`/marketplace/instructor/saas-summary/?days=${days}`).subscribe(v=>this.data.set(v))}}

@Component({selector:'app-instructor-plan',imports:[ProfessionalNavComponent],template:`<section class="page wide"><app-professional-nav/><header class="page-head"><div><p class="eyebrow">Meu plano</p><h1>Plano atual: {{data()?.plan?.code||'FREE'}}</h1></div></header><article class="plan"><h2>Free</h2><ul><li>✓ Perfil público</li><li>✓ Contato pelo WhatsApp</li><li>✓ Estatísticas básicas</li></ul></article><article class="plan pro"><small>EM BREVE</small><h2>InstrutorProCNH Pro</h2><p>Estrutura em preparação, sem preço ou cobrança ativa.</p><ul><li>Estatísticas avançadas</li><li>Agenda profissional</li><li>Gestão de contatos</li><li>Mais recursos para o perfil</li><li>Inteligência de demanda</li></ul></article></section>`,styles:[`.plan{padding:1.5rem;margin-bottom:1rem;border:1px solid #d6e5e3;border-radius:1rem;background:#fff}.plan li{margin:.7rem 0}.pro small{color:#cc641e;font-weight:800;letter-spacing:.1em}`]})
export class InstructorPlanComponent {private http=inject(HttpClient);data=signal<SaasSummary|undefined>(undefined);constructor(){this.http.get<SaasSummary>('/marketplace/instructor/saas-summary/?days=30').subscribe(v=>this.data.set(v))}}

@Component({selector:'app-legal-placeholder',template:`<section class="page narrow"><p class="eyebrow">PENDING_CONTENT_APPROVAL</p><h1>{{title}}</h1><p>O conteúdo jurídico definitivo aguarda aprovação. Canal inicial de privacidade: <a href="mailto:focusgtba@gmail.com">focusgtba@gmail.com</a>.</p></section>`})
export class LegalPlaceholderComponent {title='Privacidade e termos'}
