# Generated by Django 5.2.17 on 2026-08-24 02:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorization', models.CharField(choices=[('RESPONSIBLE', 'Responsável'), ('ADMINISTRATOR', 'Administrador')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.clinic')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_memberships', to='people.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('clinic', 'person'), name='uq_clinic_person')],
            },
        ),
    ]
