# Generated by Django 5.2.17 on 2026-08-29 07:21

import apps.organizations.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('cnpj', models.CharField(blank=True, help_text='Somente números; a formatação é aceita no painel.', max_length=14, validators=[apps.organizations.validators.validate_cnpj], verbose_name='CNPJ')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('business_address', models.TextField(blank=True, verbose_name='endereço empresarial')),
                ('legal_representative', models.CharField(blank=True, max_length=200, verbose_name='representante legal')),
                ('operational_contact', models.CharField(blank=True, max_length=254, verbose_name='contato operacional')),
                ('privacy_contact', models.CharField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Informe um e-mail válido para o canal de privacidade.')], verbose_name='canal de privacidade/LGPD')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('dpo_name', models.CharField(blank=True, max_length=200, verbose_name='Encarregado/DPO')),
                ('dpo_contact', models.CharField(blank=True, max_length=254, verbose_name='contato do Encarregado/DPO')),
                ('dpo_appointment_reference', models.CharField(blank=True, max_length=200, verbose_name='referência do ato de nomeação do DPO')),
                ('validation_status', models.CharField(choices=[('INCOMPLETE', 'Incompleta'), ('PENDING_VALIDATION', 'Pendente de validação'), ('VALIDATED', 'Validada')], default='INCOMPLETE', max_length=24, verbose_name='status')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validada em')),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_platform_organizations', to=settings.AUTH_USER_MODEL, verbose_name='validada por')),
            ],
            options={
                'verbose_name': 'organização / controlador',
                'verbose_name_plural': 'organização / controlador',
                'permissions': [('manage_platform_organization', 'Pode configurar a organização controladora'), ('validate_platform_organization', 'Pode validar a organização controladora')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cnpj', ''), ('cnpj__regex', '^\\d{14}$'), _connector='OR'), name='organization_cnpj_digits_or_blank')],
            },
        ),
    ]
