# Generated by Django 5.2.17 on 2026-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_platformorganization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinic",
            options={"verbose_name": "clínica", "verbose_name_plural": "clínicas"},
        ),
        migrations.AlterModelOptions(
            name="clinicmembership",
            options={
                "verbose_name": "vínculo com clínica",
                "verbose_name_plural": "vínculos com clínicas",
            },
        ),
    ]
